import Mathlib.Data.Fintype.Pi
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

/-!
# BayesianNetworksProofs.Finite.BayesNet

**Concrete finite Bayesian networks** — the semantic model behind `BayesianNetworks.jl`'s
finite stochastic evaluator (SPEC §5, §8, §10, §14).

A `FinBayesNet` is a finite type `V` of variables, a finite type `M` of mechanisms, a finite
non-empty state space `states v` for each variable, a `target` variable for each mechanism and a
finite set of `parents` for each mechanism. This is the shape of the `SchBayesNet` ACSet
(`Mechanism --target--> Variable`, `Input` rows collected into `parents`) with the attribute
data erased; kernels live outside the structure, exactly as `kernel_ref` points outside the
ACSet in Julia.

Kernels are valued in an arbitrary commutative semiring `R` (instantiate with `ℝ≥0` or `ℝ`):
`κ m x y` is the weight the mechanism `m` assigns to the value `y` of its target given the
assignment `x`. Two properties matter:

* `Local κ m` — `κ m x` depends on `x` only through the parents of `m`
  (the mechanism is a kernel `⨂ parents → target`);
* `Normalised κ m` — `∑ y, κ m x y = 1` (the kernel is a stochastic map).

`Closed bn` (exactly one mechanism per variable, `target` bijective) is `validate(bn; closed=true)`
and `TopoOrder bn` is a topological order of the derived variable graph (SPEC §11 item 7).

The joint `joint κ x = ∏ m, κ m x (x (target m))` is Proposition 1's right-hand side.
-/

namespace BayesianNetworksProofs

/-- A finite Bayesian-network *shape*: variables, mechanisms, state spaces, targets, parents. -/
structure FinBayesNet where
  /-- Variables. -/
  V : Type
  /-- Mechanisms (one per `Mechanism` row of the ACSet). -/
  M : Type
  [fintypeV : Fintype V]
  [decV : DecidableEq V]
  [fintypeM : Fintype M]
  [decM : DecidableEq M]
  /-- The finite state space of each variable. -/
  states : V → Type
  [fintypeS : ∀ v, Fintype (states v)]
  [decS : ∀ v, DecidableEq (states v)]
  [nonemptyS : ∀ v, Nonempty (states v)]
  /-- The variable generated by each mechanism (`target : Mechanism → Variable`). -/
  target : M → V
  /-- The input variables of each mechanism (the `Input` rows of the ACSet). -/
  parents : M → Finset V

attribute [instance] FinBayesNet.fintypeV FinBayesNet.decV FinBayesNet.fintypeM FinBayesNet.decM
  FinBayesNet.fintypeS FinBayesNet.decS FinBayesNet.nonemptyS

namespace FinBayesNet

variable (bn : FinBayesNet)

/-- A joint assignment of a state to every variable. -/
abbrev Assignment := ∀ v, bn.states v

/-- A family of conditional kernels, one per mechanism: `κ m x y` is the weight of the target
value `y` given the assignment `x`. -/
abbrev Kernel (R : Type) := (m : bn.M) → bn.Assignment → bn.states (bn.target m) → R

variable {bn} {R : Type}

/-- `k` depends on the assignment only through the variables in `P`. -/
def LocalOn (P : Finset bn.V) {v : bn.V} (k : bn.Assignment → bn.states v → R) : Prop :=
  ∀ x x' : bn.Assignment, (∀ p ∈ P, x p = x' p) → k x = k x'

/-- The kernel of `m` reads only the parents of `m`. -/
def Local (κ : bn.Kernel R) (m : bn.M) : Prop := LocalOn (bn.parents m) (κ m)

/-- The kernel of `m` is a stochastic map: its weights sum to one for every assignment. -/
def Normalised [AddCommMonoid R] [One R] (κ : bn.Kernel R) (m : bn.M) : Prop :=
  ∀ x, ∑ y, κ m x y = 1

/-- Closed network: every variable has exactly one generating mechanism
(`validate(bn; closed=true)`). -/
def Closed (bn : FinBayesNet) : Prop := Function.Bijective bn.target

/-- A topological order of the variables: a duplicate-free, complete list in which every parent
of a mechanism precedes the mechanism's target, and no mechanism reads its own target. -/
structure TopoOrder (bn : FinBayesNet) where
  order : List bn.V
  nodup : order.Nodup
  complete : ∀ v, v ∈ order
  /-- For `a` before `b` in the order, `b` is not a parent of the mechanism generating `a`. -/
  parents_before : order.Pairwise (fun a b => ∀ m, bn.target m = a → b ∉ bn.parents m)
  no_self : ∀ m, bn.target m ∉ bn.parents m

/-- The joint weight of an assignment: the product of all mechanism kernels evaluated at it
(Proposition 1, right-hand side). -/
def joint [CommMonoid R] (κ : bn.Kernel R) (x : bn.Assignment) : R :=
  ∏ m, κ m x (x (bn.target m))

end FinBayesNet

end BayesianNetworksProofs
