"""
Canonical renumbering. ACSet equality (`==`) is sensitive to part numbering, so two
networks built in different orders compare unequal even when they describe the same
structure. `canonicalize` renumbers parts deterministically from the data alone.
"""

"""
    canonicalize(bn::AbstractBayesNet) -> typeof(bn)

A copy of `bn` whose parts are renumbered deterministically: variables sorted by
`(variable_name, old id)`, states by `(variable, state_position, old id)`, mechanisms
by `(target, mechanism_name, old id)` and inputs by `(mechanism, input_position, old
id)`. Two networks that differ only in construction order have `==` canonical forms.

The order is name-sensitive: when several variables share a name, ties are broken by
the old part ids, so canonical forms of such networks can differ even when the networks
are isomorphic. See [`is_isomorphic`](@ref).
"""
function canonicalize(bn::AbstractBayesNet)
    return _canonical_copy(bn, sort(variables(bn); by=v -> (variable_name(bn, v), v)))
end

# The canonical form of `bn` for a given ordering of its variables. `canonicalize` uses
# the ordering by `(variable_name, old id)`; `is_isomorphic` walks the other orderings
# that only permute equally named variables.
function _canonical_copy(bn::AbstractBayesNet, old_vars::AbstractVector{Int})
    out = constructor(bn)()
    new_var = Dict{Int,Int}()
    for v in old_vars
        new_var[v] = add_part!(out, :Variable; variable_name=variable_name(bn, v),
                               space_ref=subpart(bn, v, :space_ref))
        for s in state_ids(bn, v)
            add_part!(out, :State; state_variable=new_var[v],
                      state_name=subpart(bn, s, :state_name),
                      state_position=subpart(bn, s, :state_position))
        end
    end
    old_mechs = sort(mechanisms(bn);
                     by=m -> (get(new_var, subpart(bn, m, :target), 0),
                              mechanism_name(bn, m), m))
    for m in old_mechs
        t = subpart(bn, m, :target)
        new_m = add_part!(out, :Mechanism; target=get(new_var, t, 0),
                          mechanism_name=mechanism_name(bn, m),
                          kernel_ref=subpart(bn, m, :kernel_ref))
        for i in input_ids(bn, m)
            add_part!(out, :Input; input_mechanism=new_m,
                      input_variable=get(new_var, subpart(bn, i, :input_variable), 0),
                      input_position=subpart(bn, i, :input_position))
        end
    end
    return out
end

"""
    is_isomorphic(a::AbstractBayesNet, b::AbstractBayesNet; max_orderings = 100_000) -> Bool

Whether `a` and `b` are the same network up to renumbering of parts, with all
attributes (names, positions, references) required to agree. Computed as equality of
[`canonicalize`](@ref)d forms, which is exact when variable and mechanism names are
unique.

When names repeat, the canonical form is not unique: the only freedom an isomorphism
has is to permute variables that share a name (states and inputs are ordered by
`state_position` and `input_position`, and mechanisms by their target and name), so the
remaining orderings are searched exhaustively. `max_orderings` caps that search; a
network whose equally named variables admit more orderings than this throws
[`ModelTooLargeError`](@ref).
"""
function is_isomorphic(a::AbstractBayesNet, b::AbstractBayesNet;
                       max_orderings::Integer=100_000)
    canonicalize(a) == canonicalize(b) && return true
    _names_unique(a) && _names_unique(b) && return false
    return _isomorphic_by_search(a, b, max_orderings)
end

function _names_unique(bn::AbstractBayesNet)
    return allunique(subpart(bn, :variable_name)) && allunique(subpart(bn, :mechanism_name))
end

# Variable ids of `bn` grouped by name, each group in ascending id order, the groups in
# the order the names appear in a canonical ordering.
function _name_groups(bn::AbstractBayesNet)
    order = sort(variables(bn); by=v -> (variable_name(bn, v), v))
    groups = Vector{Int}[]
    for v in order
        if !isempty(groups) &&
           variable_name(bn, first(last(groups))) == variable_name(bn, v)
            push!(last(groups), v)
        else
            push!(groups, Int[v])
        end
    end
    return groups
end

# Exhaustive search over the variable orderings that permute equally named variables,
# comparing canonical forms. `Combinatorics` is not a dependency, so the permutations of
# each group are generated by insertion.
function _permutations(xs::Vector{Int})
    length(xs) <= 1 && return [copy(xs)]
    out = Vector{Int}[]
    for p in _permutations(xs[2:end]), i in 0:length(p)
        push!(out, vcat(p[1:i], xs[1], p[(i + 1):end]))
    end
    return out
end

function _isomorphic_by_search(a::AbstractBayesNet, b::AbstractBayesNet,
                               max_orderings::Integer)
    groups = _name_groups(a)
    total = prod(BigInt[factorial(big(length(g))) for g in groups]; init=big(1))
    total <= max_orderings ||
        throw(ModelTooLargeError(Int(min(total, typemax(Int))), Int(max_orderings)))
    target = canonicalize(b)
    perms = [_permutations(g) for g in groups]
    for choice in Iterators.product(perms...)
        _canonical_copy(a, reduce(vcat, choice; init=Int[])) == target && return true
    end
    return false
end
