"""
Read-only accessors. Every function accepts variables and mechanisms either as part ids
or as names, and returns part ids unless its name says otherwise.

Ordering contract: `states` are sorted by `state_position`, `parents` and `inputs` by
`input_position`. Part-id order is never used to define an order.
"""

# Variables and states
######################

"""
    variables(bn) -> Vector{Int}

Part ids of all variables.
"""
variables(bn::AbstractVariableSpace) = collect(parts(bn, :Variable))

"""
    variable_names(bn) -> Vector{Symbol}

Names of all variables, in part-id order.
"""
variable_names(bn::AbstractVariableSpace) = collect(subpart(bn, :variable_name))

"""
    variable_name(bn, v) -> Symbol

Name of variable `v` (a part id).
"""
variable_name(bn::AbstractVariableSpace, v::Integer) = subpart(bn, Int(v), :variable_name)

"""
    has_variable(bn, name::Symbol) -> Bool

Whether some variable is called `name`.
"""
function has_variable(bn::AbstractVariableSpace, name::Symbol)
    return !isempty(incident(bn, name,
                             :variable_name))
end

"""
    state_ids(bn, v) -> Vector{Int}

Part ids of the states of variable `v` (id or name), sorted by `state_position`.
"""
function state_ids(bn::AbstractVariableSpace, v)
    ids = collect(incident(bn, _variable_id(bn, v), :state_variable))
    return sort!(ids; by=s -> (subpart(bn, s, :state_position), s))
end

"""
    states(bn, v) -> Vector{Symbol}

State names of variable `v` (id or name), sorted by `state_position`.
"""
function states(bn::AbstractVariableSpace, v)
    return [subpart(bn, s, :state_name)
            for s in state_ids(bn, v)]
end

"""
    nstates(bn, v) -> Int

Number of states of variable `v` (id or name).
"""
function nstates(bn::AbstractVariableSpace, v)
    return length(incident(bn, _variable_id(bn, v),
                           :state_variable))
end

"""
    space_ref(bn, v) -> KernelRef

The `space_ref` attribute of variable `v` (id or name).
"""
space_ref(bn::AbstractVariableSpace, v) = subpart(bn, _variable_id(bn, v), :space_ref)

# Mechanisms and inputs
#######################

"""
    mechanisms(bn) -> Vector{Int}

Part ids of all mechanisms.
"""
mechanisms(bn::AbstractBayesNet) = collect(parts(bn, :Mechanism))

"""
    mechanism_names(bn) -> Vector{Symbol}

Names of all mechanisms, in part-id order.
"""
mechanism_names(bn::AbstractBayesNet) = collect(subpart(bn, :mechanism_name))

"""
    mechanism_name(bn, m) -> Symbol

Name of mechanism `m` (a part id).
"""
mechanism_name(bn::AbstractBayesNet, m::Integer) = subpart(bn, Int(m), :mechanism_name)

"""
    kernel_ref(bn, m) -> KernelRef

The `kernel_ref` attribute of mechanism `m` (id or name).
"""
kernel_ref(bn::AbstractBayesNet, m) = subpart(bn, _mechanism_id(bn, m), :kernel_ref)

"""
    target(bn, m) -> Int

Part id of the variable generated by mechanism `m` (id or name).
"""
target(bn::AbstractBayesNet, m) = subpart(bn, _mechanism_id(bn, m), :target)

"""
    input_ids(bn, m) -> Vector{Int}

`Input` part ids of mechanism `m` (id or name), sorted by `input_position`.
"""
function input_ids(bn::AbstractBayesNet, m)
    ids = collect(incident(bn, _mechanism_id(bn, m), :input_mechanism))
    return sort!(ids; by=i -> (subpart(bn, i, :input_position), i))
end

"""
    inputs(bn, m) -> Vector{Int}

Part ids of the input (parent) variables of mechanism `m` (id or name), sorted by
`input_position`.
"""
function inputs(bn::AbstractBayesNet, m)
    return [subpart(bn, i, :input_variable)
            for i in input_ids(bn, m)]
end

"""
    mechanism_of(bn, v) -> Union{Int, Nothing}

Part id of the mechanism generating variable `v` (id or name), or `nothing` if the
variable is exogenous. Throws [`DuplicateGeneratorError`](@ref) if there are several.
"""
function mechanism_of(bn::AbstractBayesNet, v)
    vid = _variable_id(bn, v)
    ms = incident(bn, vid, :target)
    isempty(ms) && return nothing
    length(ms) > 1 &&
        throw(DuplicateGeneratorError(variable_name(bn, vid), vid, collect(ms)))
    return first(ms)
end

"""
    has_mechanism(bn, v) -> Bool

Whether variable `v` (id or name) has at least one generating mechanism.
"""
function has_mechanism(bn::AbstractBayesNet, v)
    return !isempty(incident(bn, _variable_id(bn, v),
                             :target))
end

"""
    parents(bn, v) -> Vector{Int}

Part ids of the parents of variable `v` (id or name): the inputs of its mechanism,
sorted by `input_position`. Exogenous variables have no parents. Use
[`inputs`](@ref) to query a mechanism directly.
"""
function parents(bn::AbstractBayesNet, v)
    m = mechanism_of(bn, v)
    return m === nothing ? Int[] : inputs(bn, m)
end

"""
    children(bn, v) -> Vector{Int}

Part ids of the variables whose mechanisms take `v` (id or name) as an input, sorted
and without repetition.
"""
function children(bn::AbstractBayesNet, v)
    vid = _variable_id(bn, v)
    ms = subpart(bn, incident(bn, vid, :input_variable), :input_mechanism)
    return sort!(unique!([subpart(bn, m, :target) for m in ms]))
end

"""
    exogenous(bn) -> Vector{Int}

Part ids of the variables without a generating mechanism.
"""
exogenous(bn::AbstractBayesNet) = filter(v -> !has_mechanism(bn, v), variables(bn))

"""
    roots(bn) -> Vector{Int}

Part ids of the variables without parents: exogenous variables and variables whose
mechanism has no inputs.
"""
roots(bn::AbstractBayesNet) = filter(v -> isempty(parents(bn, v)), variables(bn))

# The (name, position) pairs of the states of variable `v`, in position order: the
# comparable form of a variable's state set, used by `dynamic.jl` to check that a
# lagged variable carries the same states as its base and by
# `CategoricalBayesianNetworks.jl` to compare open-network interfaces.
function _state_table(vs::AbstractVariableSpace, v)
    return [(subpart(vs, s, :state_name), subpart(vs, s, :state_position))
            for s in state_ids(vs, v)]
end
